name: ResourceRush
version: '1.1-SNAPSHOT'
main: wueffi.resourcerush.ResourceRush
api-version: '1.21'
load: POSTWORLD
authors: [ "Waffle [Wueffi]" ]
description: Plugin for the Collab-a-ton 1000x1000 ResourceRush Event

commands:
  playtime:
    description: Check your own playtime for today.
    usage: /playtime
  check:
    description: Check another player's score.
    usage: /check <player>
  start:
    description: Start playing the survival event.
    usage: /start
  end:
    description: End playing the survival event.
    usage: /end
  leaderboard:
    description: Show the leaderboard of the survival event.
    usage: /leaderboard <integer>
  hologram:
    description: Add leaderboard holograms